# If you add a page, you must add it to the index here
pages:
  - Home: 'index.md'
  - GENERAL:
    - FAQ: 'general/faq.md'
    - Installation Guide: 'general/installation_guide.md'
    - Uninstallation: 'general/uninstallation.md'
    - License: 'general/license.md'
    - Translation: 'general/translation.md'
    - Upgrade Version: 'general/upgrade_version.md'
    - Purchase, Payment and Invoices: 'general/purchase_payment_and_invoices.md'
    - Support: 'general/support.md'
  - MAGENTO 1:
    - Defer JavaScript: 'magento1/defer_javascript.md' 
    - Minimum Order Amount for Customer Group : 'magento1/minimum_order_amount_for_customer_group.md' 
    - Multistore Pricing: 'magento1/multistore_pricing.md' 
    - Wholesale Fast Order: 'magento1/wholesale_fast_order.md'
    - Configurable Product Grid Table View: 'magento1/configurable_product_grid_table_view.md'
    - Pro Configurable Product Grid Table View: 'magento1/pro_configurable_product_grid_table_view.md'
    - Delete Order: 'magento1/delete_order.md'
    - Order Delivery Date: 'magento1/order_delivery_date.md'
    - Lazy Image Loader:  'magento1/lazy_image_loader.md'
    - Auto Invoice: 'magento1/auto_invoice.md'
  - MAGENTO 2:
    - Defer Javascript: 'magento2/defer_js.md'
    - Minimum Order Amount for Customer Group:  'magento2/minimum_order_amount_for_customer_group.md'
    - Lazy Image Loader:  'magento2/lazy_image_loader.md'
  - HOW TO:
    - Topics: 'howto.md'

# Do not edit in PRs below here
site_name: BSSCommerce Wiki

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

extra_css:
  - css/styles.css

theme: readthedocs

title: " BSSCommerce Wiki latest documentation "

site_favicon: bsscommerce_logo.png